In [21]:
import numpy as np

Print NumPy version

In [22]:
print(np.__version__)

2.2.2


Creatin arrays from Python Lists

In [23]:
# Integer array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Setting the type explicitly when creating an array

In [24]:
np.array([1, 2, 3], dtype = np.float32)

array([1., 2., 3.], dtype=float32)

Creating multi-dimensional arrays from nested lists

In [25]:
# Nested lists create multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating arrays from scratch

In [26]:
# Create a length 10 array filled with 0s
x10 = np.zeros(10, dtype=int)
print(x10)

[0 0 0 0 0 0 0 0 0 0]


In [27]:
# Create a 3x5 floating point array filled with 1s
x35 = np.ones((3, 5), dtype=float)
print(x35)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# Create a 3x5 array filled with Pi
xpi = np.full((3, 5), 3.14)
print(xpi)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [29]:
# Create an array filled with a sequence starting at 0, ending at 20 and steps of 2
xseq = np.arange(0, 20, 2)
print(xseq)

[ 0  2  4  6  8 10 12 14 16 18]


In [30]:
# Create an array of 5 values evenly spaced between 0 and 1
xdist = np.linspace(0, 1, 5)
print(xdist)

[0.   0.25 0.5  0.75 1.  ]


In [31]:
# Create a 3x3 array of uniformly distributed pseudorandom values between 0 and 1
xrand = np.random.random((3, 3))
print(xrand)

[[0.17527927 0.38894877 0.90910734]
 [0.09923768 0.00490162 0.85319256]
 [0.80215381 0.90641362 0.17842029]]


In [32]:
# Create a 3x3 array of normally distributed pseudorandom values with a mean of 0 and standard deviation of 1
xstd = np.random.normal(0, 1, (3, 3))
print(xstd)

[[-0.52482006  1.65070317 -0.11899014]
 [ 0.85913504 -2.3214682   1.19729531]
 [ 0.25469108  0.30831095 -1.24028997]]


In [33]:
# Create a 3x3 matrix of pseudorandom values between 0 and 10
xprand = np.random.randint(0, 10, (3, 3))
print(xprand)

[[8 1 2]
 [5 3 2]
 [6 3 6]]


In [34]:
# Create an identity matrix
xiden = np.eye(3)
print(xiden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


-------------------------------------------BASICS OF NUMPY ARRAYS-----------------------------------------

Create a random number generator and seed it

In [35]:
rng = np.random.default_rng(seed=170)

Create 1d, 2d and 3d array

In [36]:
x1 = rng.integers(10, size=6) #1d array
x2 = rng.integers(10, size=(3, 4)) #2d array
x3 = rng.integers(10, size=(3, 4, 5)) #3d array

ndim - number of dimensions, shape - the size of each dimension, size - the total size of the array and dtype - the type of each element

In [37]:
print(f'x3 dim: {x3.ndim}')
print(f'x3 shape: {x3.shape}')
print(f'x3 size: {x3.size}')
print(f'x3 dtype: {x3.dtype}')

x3 dim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64


Array Indexing

In [38]:
print(f'x1: {x1}')
print(f'{x1[3]}')
print(f'{x1[-1]}')

x1: [7 7 6 9 3 8]
9
8


In [39]:
print(f'x2: {x2}')
print(f'{x2[2, 3]}')
print(f'{x2[0, -1]}')

x2: [[3 9 3 1]
 [7 9 6 0]
 [0 0 2 6]]
6
1


Array Slicing

In [40]:
print(f'x1: {x1}')
print(f'First 3 elements of x1: {x1[:3]}')
print(f'Alternate elements starting with the second element of x1: {x1[1::2]}')
print(f'Alternate elements of x1 starting from the last element: {x1[-1::2]}')

x1: [7 7 6 9 3 8]
First 3 elements of x1: [7 7 6]
Alternate elements starting with the second element of x1: [7 9 8]
Alternate elements of x1 starting from the last element: [8]


Multi-dimensional sub-arrays

In [45]:
print(f'x2: {x2}')
print(f'First 2 rows and 3 columns of x2: {x2[:2, :3]}')
print(f'Every second column of all 3 rows of x2:{x2[:, ::2]}')
print(f'All rows and columns reversed for x2:{x2[::-1,::-1]}')

x2: [[3 9 3 1]
 [7 9 6 0]
 [0 0 2 6]]
First 2 rows and 3 columns of x2: [[3 9 3]
 [7 9 6]]
Every second column of all 3 rows of x2:[[3 3]
 [7 6]
 [0 2]]
All rows and columns reversed for x2:[[6 2 0 0]
 [0 6 9 7]
 [1 3 9 3]]


Selectively extracting rows and columns

In [46]:
print(f'Last column of x2: {x2[:, -1]}')
print(f'First row of x2: {x2[0, :]}')

Last column of x2: [1 0 6]
First row of x2: [3 9 3 1]


Sub-arrays as No-copy Views

In [47]:
print(f'A 2x2 sub-array extracted from x2 by selecting first two columns of first two rows: {x2[:2, :2]}')
print('Any modifications to elements of the above array will modify the original array (x2) as well.')


A 2x2 sub-array extracted from x2 by selecting first two columns of first two rows: [[3 9]
 [7 9]]
Any modifications to elements of the above array will modify the original array (x2) as well.


Creating copies of Arrays

In [48]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 9]
 [7 9]]


Reshaping of Arrays - the size of the initial array must be equal to the size of the re-shaped array.

In [49]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
grid = np.array([x for x in range(1, 10)])
# Reshaping grid to a row vector
print(grid.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [51]:
# Reshaping row vector to column vector
print(grid.reshape(9, 1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [52]:
print(grid[np.newaxis, :])

[[1 2 3 4 5 6 7 8 9]]


In [53]:
print(grid[:, np.newaxis])

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Concatenation and splitting of Arrays

In [54]:
x1 = np.array([x for x in range(1, 6)])
x2 = np.array([x for x in range(6, 11)])
x_con = np.concatenate([x1, x2])
print(x_con)

[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
x_grid = np.array([[1, 2, 3],
                   [4, 5, 6]])
x_grid_con = np.concatenate([x_grid, x_grid])
print(x_grid_con)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [56]:
x_grid_con = np.concatenate([x_grid, x_grid], axis=1)
print(x_grid_con)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [57]:
# For working with arrays of mixed dimensions, it can be clearer to use np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [58]:
x_vstack = np.vstack([x1, x2])
print(x_vstack)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [59]:
x_hstack = np.hstack([x1, x2])
print(x_hstack)

[ 1  2  3  4  5  6  7  8  9 10]


In [63]:
column_array = [[100],
                [100]]
x_vhstack = np.hstack([x_vstack, column_array])
print(x_vhstack)

[[  1   2   3   4   5 100]
 [  6   7   8   9  10 100]]


In [64]:
x1, x2, x3 = np.split(x_hstack, [3, 6])
print(x1, x2, x3)

[1 2 3] [4 5 6] [ 7  8  9 10]


In [65]:
grid = np.arange(16).reshape(4, 4)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [66]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
